### PR TITLE
[JENKINS-36184] Update envinject-lib dependency

### PR DESCRIPTION
**Pull request by fbelzunc**
https://issues.jenkins-ci.org/browse/JENKINS-36184

```
jun 23, 2016 1:24:01 PM hudson.model.Executor finish1
SEVERE: Executor threw an exception
java.lang.NoClassDefFoundError: hudson/matrix/MatrixRun
    at org.jenkinsci.lib.envinject.service.EnvInjectActionRetriever.getEnvInjectAction(EnvInjectActionRetriever.java:25)
    at org.jenkinsci.lib.envinject.service.EnvVarsResolver.getEnVars(EnvVarsResolver.java:56)
    at hudson.plugins.batch_task.BatchRun.run(BatchRun.java:224)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: java.lang.ClassNotFoundException: hudson.matrix.MatrixRun
    at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
    at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
    at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 5 more
```

I think perhaps the right fix should be on `lib.envinject` but this will not be an immediate solution.

What do you think?

@reviewbybees

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by varmenise** [comment]
🐝

**Comment by oleg-nenashev** [comment]
I'd better remove the scope at all.
Optional looks very suspicious, because the dependency should be mandatory.
And I;m not sure what it actually fixes. The code would not compile if there is a real dependency

**Comment by fbelzunc** [comment]
@oleg-nenashev Me neither - I have no clue where is the magic here.

**Comment by amuniz** [comment]
@oleg-nenashev the dependency is transitive (through `envinject-lib`). Is there some problem on adding the dependency on the lib instead of here?

**Comment by fbelzunc** [comment]
@amuniz let me try it

**Comment by alvarolobato** [comment]
Te problem actually seems to be in EnvinJect-lib which is using it and doesn't declare the dependency:
[LibInject->MatrixRun](https://github.com/jenkinsci/envinject-lib/blob/35493440358c9255ac270150de8cc72cfa152a5c/src/main/java/org/jenkinsci/lib/envinject/service/EnvInjectActionRetriever.java#L25)

**Comment by fbelzunc** [comment]
@alvarolobato DONE here: https://github.com/jenkinsci/envinject-lib/pull/7 Can I get your bee?

**Comment by fbelzunc** [comment]
BTW Good catch!

**Comment by alvarolobato** [comment]
🐝 provided it works. Should be released after envinject 1.24

**Comment by alvarolobato** [comment]
actually @fbelzunc thinking about it, what happens if the Matrix plugin is not installed?. Can you make a quick test?, I suspect it will fail too. Maybe we should change the code on envinject to check that the MatrixRun class exists

**Comment by fbelzunc** [comment]
@alvarolobato We are testing it... but if it is not installed it is a plugin dependency issue like happens in a lot of plugins, doesn't it? So I think this should be fine...

**Comment by dariver** [comment]
@alvarolobato @fbelzunc AFAIK Matrix plugin is a bundle plugin in 1.565.1 version

**Comment by fbelzunc** [comment]
@oleg-nenashev @alvarolobato Can I have your bee here?

**Comment by oleg-nenashev** [comment]
🐝

**Comment by alvarolobato** [comment]
🐝

**Comment by fbelzunc** [comment]
@reviewbybees done

**Pull request merged**
