### PR TITLE
Upgrade POM (parent POM, minimum jenkins version, etc)

### PR DESCRIPTION
**Pull request by lacostej**
### Testing done

This is a work-in-progress, and an attempt to see if the CI builds are still triggered for this plugin.

The only testing done right now are the unit tests. One of them isn't passing anymore so it will have to be fixed in subsequent commit.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by gounthar** [comment]
Could anyone please replay this PR build with the updated Jenkinsfile?

**Comment by MarkEWaite** [comment]
> Could anyone please replay this PR build with the updated Jenkinsfile?

Done

**Review by gounthar — APPROVED** [review]
Looks good to me, thanks a lot for the contribution. 👍 
[Windows build](https://ci.jenkins.io/job/Plugins/job/batch-task-plugin/job/PR-9/6/pipeline-console/?selected-node=85) outputs ` [INFO] BUILD SUCCESS` but is marked as failed. 🤔 

```
java.lang.AssertionError: 
Expected 2-1:global-property:bar:anonymous in task output: [execute] $ cmd /c call C:\Jenkins\agent\workspace\Plugins_batch-task-plugin_PR-9\target\tmp\jenkins4380962449825284861.bat

C:\Jenkins\agent\workspace\Plugins_batch-task-plugin_PR-9\target\tmp\j h11703619928117714569\workspace\execute>echo "1-1:global-property:bar:anonymous" 
"1-1:global-property:bar:anonymous"

C:\Jenkins\agent\workspace\Plugins_batch-task-plugin_PR-9\target\tmp\j h11703619928117714569\workspace\execute>exit 0 

	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at hudson.plugins.batch_task.BatchTaskTest.testExecute(BatchTaskTest.java:105)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:655)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by lacostej** [comment]
> 2-1:global-property:bar:anonymous

Well this is weird. I had to change the test expectations in 07492690ea426ce924f2064ff5b1ed915ed8615e to that the expected $TASK_ID in the string would match the output (on Mac/Linux).

This is because it appears that the tests scheduled 2 builds and then the build number is increased twice.

```
        p.scheduleBuild2(0);
        FreeStyleBuild freeStyleBuild = p.scheduleBuild2(0).get();
```

Is there anything obvious that would explain why on Windows the build number is only increased once?

This test code is 15 years old.

**Pull request merged**
